name: TraceMe
description: A simple Flutter project that ilustrates contact tracing using Wifi

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  equatable: ^1.2.0
  wifi_flutter: ^0.1.0+1
  wifi_iot: ^0.1.1
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

 
 
 
  uses-material-design: true

 
 
 
 

 
 

 
 

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
